name: E2E Regression Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
#  schedule:
#    - cron: '* * * * *'
  workflow_dispatch:

env:
  TARGET: "%regex[.*Tests.*],automationexercises.tests.**.**,automationexercises.tests.**"

jobs:
  Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Running Tests
        continue-on-error: true
        run: mvn test -Dtest="${TARGET}" -DexecutionType="LocalHeadless" -DbrowserType="Chrome" clean test

      - name: Upload test resutls
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux_Report
          path: "test-output/reports/*.html"

  Chrome_Windows_Test:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Running Tests
        continue-on-error: true
        run: mvn test -Dtest="${TARGET}" -DexecutionType="LocalHeadless" -DbrowserType="Chrome" clean test

      - name: Upload test resutls
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Windows_Report
          path: "test-output/reports/*.html"

